version: '3.4'

services:
  postgres:
    container_name: "postgres"
    image: "dwd-postgres"
    build:
      context: ./dev-db
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres_password
    ports:
      - '5432:5432'
