version: '3.4'

services:
  harvester:
    image: "dwd-radolan-tree-harvester"
    build:
      context: ./harvester
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: ./harvester/.env

  postgres:
    container_name: "postgres"
    image: "dwd-postgres"
    build:
      context: ./dev-db
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres_password
    ports:
      - '5432:5432'
