name: harvester

on:
  push:
    branches:
      - master
    paths:
      - trigger.txt
  schedule:
    # run every 5 minutes
    # - cron: '*/5 * * * *'
    # Run at 0300 daily
    - cron: '0 3 * * *'

env:
  PG_SERVER: ${{ secrets.PG_SERVER }}
  PG_PORT: 5432
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASS: ${{ secrets.PG_PASS }}
  PG_DB: ${{ secrets.PG_DB }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  OUTPUT: True

jobs:
  harvest:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      # - name: Get the source
        # uses: actions/checkout@v2
      # - name: Run postgres db (test)
        # run: docker-compose -f docker-compose.postgres.yml up -d
      - name: Run the Harvester container
        run: docker run -e PG_SERVER -e PG_PORT -e PG_USER -e PG_PASS -e PG_DB -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e S3_BUCKET -e OUTPUT -p 5432:5432 technologiestiftung/dwd-radolan-tree-harvester:test
